version: "2"
services:
  web:
    build: .
    ports:
    - "7107:7107"
    depends_on:
    - mongo
    restart: always
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./data:/data/db